In [7]:
import zipfile
with zipfile.ZipFile("../data/raw/Archive.zip","r") as zip_ref:
    zip_ref.extractall("../data/raw/")

In [3]:
import pandas as pd

In [10]:
df_orders = pd.read_csv('../data/raw/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [11]:
# Reading data
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='str')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [12]:
df_products = pd.read_csv("../data/raw/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [ ]:
import pandas as pd
SQL_URL = "https://raw.githubusercontent.com/hovhannisyan91/sql/analytics/portfolio/refs/heads/main/data/public_schema/"
TO_SAVE_URL = 'C:/Users/Lil/OneDrive/Desktop/aca/sql/portfolio/data/public_schema/'
l = ['customers', 'employees','orders','products', 'sales']

for i in l:
    print(100*'-')
    print(f"trying to download {i}.csv")
    df = pd.read_csv(SQL_URL+i+'.csv')
    print(f"{i}.csv is downloaded")
    print(f"the shape of {i}.csv : {df.shape}")
    print(f"trying to save  {i}.csv")
    df.to_csv(TO_SAVE_URL+i+'.csv',index=False)
    print(f"{i}.csv is successfully saved")

----------------------------------------------------------------------------------------------------
trying to download customers.csv
customers.csv is downloaded
the shape of customers.csv : (2000, 5)
trying to save  customers.csv
customers.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download employees.csv
employees.csv is downloaded
the shape of employees.csv : (100, 5)
trying to save  employees.csv
employees.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download orders.csv
orders.csv is downloaded
the shape of orders.csv : (200, 5)
trying to save  orders.csv
orders.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download products.csv
products.csv is downloaded
the shape of products.csv : (100, 5)
trying to save  products.csv
products.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download sales.csv
sales.csv is downloaded
the shape of sales.csv : (5000, 8)
trying to save  sales.csv
sales.csv is successfully saved

In [ ]:
df_orders_new = df_orders.astype({"order_id": "int64"})

NameError: name 'df_orders' is not defined